### ISSUE TITLE
Relay board schematic is missing 

### ISSUE THREAD

**Issue by paulsteigel** [tvixen/230V-Inverter#2]
Hi Tim,
Thank you very much for your beautiful products. I studied the advance board and found that you have connection 2 to relay board print but I could not find it in your document package. I assumed that the relay board is not needed for the Inverter (advanced version)
If it possible, please share with us the schematic and also the relay board (if needed for the inverter to work).
I am thinking on joining the Inverter with a buck converter for my home solar panels and may consider replacing nano with ESP32 wifi can also work.
Please advise me with thanks.
Yours very faithfully,
Dang Dinh Ngoc

**Comment by tvixen** [comment]
Hi Dang 
You are right, the relay board is not necessary but only a safety device that facilitates the timing of the charge and discharge for the the large electrolytes. It can charge them and discharge them with resistors and relays. 
I haven't any schematics for the relay board, but its very simple to make for other engineers.

Replacing the nano with a ESP32 is a good idea, as it have a more powerfull cpu.

**Comment by chetosvsgeez** [comment]
Sorry Tvixen I am again, you could provide me with a couple of things, with which program you made the PCBs, I know that it has no component list, but a photo of the end of the project, and an image with more resolution of the investor's scheme To try to export it to Kicad
I have already received the PCBs, the EGS002, the power supply
I only have to collect the components
For that, I need help and advice
sorry for my english
