### ISSUE TITLE
Materials Electronic PCB

### ISSUE THREAD

**Issue by chetosvsgeez** [tvixen/230V-Inverter#3]
Good afternoon you would have the list of electronic components of the three plates

**Comment by tvixen** [comment]
Sorry no BOM list .... As thers so few components.

**Comment by chetosvsgeez** [comment]
You could supply photos of the final assembly, there is a possibility of managing two series investors
Podias suministrar fotos del montaje final, hay posibilidad de gestionar dos inversores en serie
I want to ride two and try to communicate them with my axper King 5kw 48v
Quiero montar dos y intentar comunicarlos con mi axper king 5kw 48V

**Comment by chetosvsgeez** [comment]
Thank you for your work

**Comment by tvixen** [comment]
Your welcome.
